services:
  nginx:
    image: ${DOCKER_IMAGE}:dev
    container_name: ${APPLICATION_NAME}
    ports:
      - "${NGINX_PORT_HTTP}:80"
      - "${NGINX_PORT_HTTPS}:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - mumulbo-network

networks:
  mumulbo-network:
    external: true
    name: ${MMB_DOCKER_NETWORK}