services:
  nginx:
    image: ${DOCKER_IMAGE}
    container_name: mumulbo-nginx
    ports:
      - "${NGINX_PORT_HTTP}:80"
      - "${NGINX_PORT_HTTPS}:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - mumulbo-network

networks:
  mumulbo-network:
    external: true