- name: Deploy to EC2
  uses: appleboy/ssh-action@v0.1.8
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_KEY }}
    script: |
      echo "==== NETWORK TEST ===="
      ping -c 3 google.com || true
      nslookup registry-1.docker.io || true
      curl -s https://registry-1.docker.io/v2/ || true

      echo "==== WAIT FOR Docker Hub Image ===="
      for i in {1..5}; do
        curl -s https://hub.docker.com/v2/repositories/mumulbo/mmb-frontend/tags/dev | grep '"name":' && break
        echo "⏳ Image not found yet on Docker Hub... retrying in 5s"
        sleep 5
      done

      echo "==== DOCKER PULL ===="
      for i in {1..3}; do
        docker pull mumulbo/mmb-frontend:dev && break || sleep 5
      done

      docker image inspect mumulbo/mmb-frontend:dev > /dev/null 2>&1
      if [ $? -ne 0 ]; then
        echo "❌ docker pull failed, aborting deployment"
        exit 1
      fi

      echo "==== DOCKER COMPOSE UP ===="
      cd /home/ec2-user/infra
      docker-compose --env-file .env.dev up -d --no-deps --force-recreate mmb-frontend
