name: Frontend Dev CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t mumulbo/mmb-frontend:dev --build-arg VITE_ENV=dev .

      - name: Push Docker image
        run: docker push mumulbo/mmb-frontend:dev

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull mumulbo/mmb-frontend:dev
            cd /home/ec2-user/infra
            docker-compose --env-file .env.dev up -d --no-deps --force-recreate mmb-frontend

      # 10. 이메일 알림 (성공 여부에 따라)
      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "MMB Frontend Deployment - ${{ job.status }}"
          body: |
            The MMB frontend deployment via GitHub Actions has completed.
            Status: ${{ job.status }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Run ID: ${{ github.run_id }}
          to: ${{ secrets.RECIPIENT }}
          from: ${{ secrets.SMTP_USER }}
          secure: false
          ignore_cert: false