name: Deploy Frontend via Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설치
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 프로젝트 빌드
      - name: Build project
        run: npm run build

      # 5. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/mmb-frontend:latest .

      # 6. Docker Hub 로그인
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 7. Docker 이미지 푸시
      - name: Push Docker image
        run: |
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/mmb-frontend:latest

      # 8. EC2에 배포
      - name: Deploy on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/mmb-frontend:latest
        run: |
          echo "${{ secrets.EC2_KEY }}" > /tmp/key.pem
          chmod 400 /tmp/key.pem
          ssh -o StrictHostKeyChecking=no -i /tmp/key.pem $EC2_USER@$EC2_HOST "
            sudo docker pull $DOCKER_IMAGE && \
            sudo docker stop mmb-frontend || true && \
            sudo docker rm mmb-frontend || true && \
            sudo docker run -d -p 80:80 --name mmb-frontend $DOCKER_IMAGE
          "